version: 2
registries:
  maven-github-uio-bmi:
    type: maven-repository
    url: 'https://maven.pkg.github.com/uio-bmi'
    username: '${{secrets.MAVEN_USER}}'
    password: '${{secrets.MAVEN_GITHUB}}'
  maven-github-elixir-oslo:
    type: maven-repository
    url: 'https://maven.pkg.github.com/elixir-oslo'
    username: '${{secrets.MAVEN_USER}}'
    password: '${{secrets.MAVEN_GITHUB}}'
updates:
- package-ecosystem: maven
  directory: "/"
  registries: "*"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
